    - job_name: kube-state-metrics
      static_configs:
      - targets:
        - 'kube-state-metrics.kube-system.svc.cluster.local:8080'
        - 'kube-state-metrics.kube-system.svc.cluster.local:8081'
