---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    # owner nobody:nogroup
    path: /srv/exports/monitoring/grafana
    server: 10.102.0.8
